###**1. COLLECTING TAYLOR SWIFT SONGS , ALBUM AND ERAS DATA**

####1.1 Downloading existing datasets from kaggle and saving it to local directory

In [37]:
from google.colab import drive

drive.mount('/content/drive')
project_folder_path = "/content/drive/MyDrive/TaylorSwiftEras/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [38]:
import kagglehub
import shutil
import os

# Download dataset
path : str = kagglehub.dataset_download(
    "joebeachcapital/taylor-swift-all-songs-and-albums"
)

print("Downloaded to:", path)

# See files inside dataset
print(os.listdir(path))

Using Colab cache for faster access to the 'taylor-swift-all-songs-and-albums' dataset.
Downloaded to: /kaggle/input/taylor-swift-all-songs-and-albums
['taylor_all_songs.csv', 'taylor_album_songs.csv', 'taylor_albums.csv']

In [39]:
source_file : str = os.path.join(path, "taylor_all_songs.csv")

destination_folder : str = os.path.join(project_folder_path , "Data/Raw")


destination_file : str = os.path.join(
    destination_folder,
    "taylor_all_songs.csv"
)

shutil.copy(source_file, destination_folder)

print("CSV copied to:", destination_folder)

CSV copied to: /content/drive/MyDrive/TaylorSwiftEras/Data/Raw

In [40]:
import pandas as pd

taylor_song_df : pd.DataFrame = pd.read_csv(destination_file)
taylor_song_df_processed : pd.DataFrame = taylor_song_df.copy()
taylor_song_df

,album_name,ep,album_release,track_number,track_name,artist,featuring,bonus_track,promotional_release,single_release,...,liveness,valence,tempo,time_signature,duration_ms,explicit,key_name,mode_name,key_mode,lyrics
0,Taylor Swift,False,2006-10-24,1.0,Tim McGraw,Taylor Swift,NaN,False,NaN,2006-06-19,...,0.1210,0.425,76.009,4.0,232107.0,False,C,major,C major,NaN
1,Taylor Swift,False,2006-10-24,2.0,Picture To Burn,Taylor Swift,NaN,False,NaN,2008-02-03,...,0.0962,0.821,105.586,4.0,173067.0,False,G,major,G major,NaN
2,Taylor Swift,False,2006-10-24,3.0,Teardrops On My Guitar,Taylor Swift,NaN,False,NaN,2007-02-19,...,0.1190,0.289,99.953,4.0,203040.0,False,A#,major,A# major,NaN
3,Taylor Swift,False,2006-10-24,4.0,A Place In This World,Taylor Swift,NaN,False,NaN,NaN,...,0.3200,0.428,115.028,4.0,199200.0,False,A,major,A major,NaN
4,Taylor Swift,False,2006-10-24,5.0,Cold As You,Taylor Swift,NaN,False,NaN,NaN,...,0.1230,0.261,175.558,4.0,239013.0,False,F,major,F major,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,NaN,NaN,NaN,NaN,Highway Don't Care,Tim McGraw,"Taylor Swift, Keith Urban",NaN,NaN,2013-03-25,...,0.0863,0.495,158.061,4.0,276880.0,False,D,major,D major,NaN
270,NaN,NaN,NaN,NaN,Renegade,Big Red Machine,Taylor Swift,NaN,NaN,2021-07-02,...,0.1070,0.586,167.977,4.0,254467.0,True,C,major,C major,NaN
271,NaN,NaN,NaN,NaN,The Joker And The Queen,Ed Sheeran,Taylor Swift,NaN,NaN,2022-02-11,...,0.2820,0.307,133.830,4.0,185422.0,False,C,major,C major,NaN
272,NaN,NaN,NaN,NaN,Three Sad Virgins,NaN,NaN,NaN,2021-11-13,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,NaN,NaN,NaN,Two Is Better Than One,Boys Like Girls,Taylor Swift,NaN,NaN,2009-10-19,...,0.0962,0.250,127.976,4.0,242840.0,False,C,major,C major,NaN

In [41]:
#Dropping null index and columns
taylor_song_df_processed : pd.DataFrame = taylor_song_df_processed.dropna(subset = ['album_name'])
taylor_song_df_processed : pd.DataFrame = taylor_song_df_processed.drop(columns = ['featuring' , 'bonus_track' , 'promotional_release' , 'single_release'])

In [42]:
taylor_song_df_processed['artist'] = taylor_song_df_processed['artist'].fillna('Taylor Swift')
taylor_song_df_processed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 247 entries, 0 to 246
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   album_name        247 non-null    object
 1   ep                247 non-null    object
 2   album_release     247 non-null    object
 3   track_number      247 non-null    float64
 4   track_name        247 non-null    object
 5   artist            247 non-null    object
 6   track_release     247 non-null    object
 7   danceability      238 non-null    float64
 8   energy            238 non-null    float64
 9   key               238 non-null    float64
 10  loudness          238 non-null    float64
 11  mode              238 non-null    float64
 12  speechiness       238 non-null    float64
 13  acousticness      238 non-null    float64
 14  instrumentalness  238 non-null    float64
 15  liveness          238 non-null    float64
 16  valence           238 non-null    float64
 17  tempo             238 non-null    float64
 18  time_signature    238 non-null    float64
 19  duration_ms       238 non-null    float64
 20  explicit          238 non-null    object
 21  key_name          238 non-null    object
 22  mode_name         238 non-null    object
 23  key_mode          238 non-null    object
 24  lyrics            0 non-null      float64
dtypes: float64(15), object(10)
memory usage: 50.2+ KB

In [43]:
taylor_song_df_processed['lyrics'] = taylor_song_df_processed['lyrics'].astype('string')
taylor_song_df_processed

,album_name,ep,album_release,track_number,track_name,artist,track_release,danceability,energy,key,...,liveness,valence,tempo,time_signature,duration_ms,explicit,key_name,mode_name,key_mode,lyrics
0,Taylor Swift,False,2006-10-24,1.0,Tim McGraw,Taylor Swift,2006-06-19,0.580,0.491,0.0,...,0.1210,0.425,76.009,4.0,232107.0,False,C,major,C major,<NA>
1,Taylor Swift,False,2006-10-24,2.0,Picture To Burn,Taylor Swift,2006-10-24,0.658,0.877,7.0,...,0.0962,0.821,105.586,4.0,173067.0,False,G,major,G major,<NA>
2,Taylor Swift,False,2006-10-24,3.0,Teardrops On My Guitar,Taylor Swift,2006-10-24,0.621,0.417,10.0,...,0.1190,0.289,99.953,4.0,203040.0,False,A#,major,A# major,<NA>
3,Taylor Swift,False,2006-10-24,4.0,A Place In This World,Taylor Swift,2006-10-24,0.576,0.777,9.0,...,0.3200,0.428,115.028,4.0,199200.0,False,A,major,A major,<NA>
4,Taylor Swift,False,2006-10-24,5.0,Cold As You,Taylor Swift,2006-10-24,0.418,0.482,5.0,...,0.1230,0.261,175.558,4.0,239013.0,False,F,major,F major,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Beautiful Eyes,True,2008-07-15,2.0,Should've Said No (Alternate Version),Taylor Swift,2008-07-15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
243,Beautiful Eyes,True,2008-07-15,3.0,Teardrops On My Guitar (Acoustic Version),Taylor Swift,2008-07-15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
244,Beautiful Eyes,True,2008-07-15,4.0,Picture To Burn (Radio Edit),Taylor Swift,2008-07-15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
245,Beautiful Eyes,True,2008-07-15,5.0,I'm Only Me When I'm With You,Taylor Swift,2008-07-15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
246,Beautiful Eyes,True,2008-07-15,6.0,I Heart ?,Taylor Swift,2008-06-23,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

In [49]:
#Filling null value in all numeric type columns with mean
numeric_cols  = taylor_song_df_processed.select_dtypes(include = ['number']).columns

for cols in numeric_cols :
  taylor_song_df_processed[cols] = taylor_song_df_processed[cols].fillna(taylor_song_df_processed[cols].mean())

#Filling null value in string and object column with mode
string_cols = taylor_song_df_processed.select_dtypes(include = ['object' , 'string']).columns

for col in string_cols:
    taylor_song_df_processed[col] = taylor_song_df_processed[col].fillna(taylor_song_df_processed[col].mode())

taylor_song_df_processed

,album_name,ep,album_release,track_number,track_name,artist,track_release,danceability,energy,key,...,liveness,valence,tempo,time_signature,duration_ms,explicit,key_name,mode_name,key_mode,lyrics
0,Taylor Swift,False,2006-10-24,1.0,Tim McGraw,Taylor Swift,2006-06-19,0.580000,0.491000,0.000000,...,0.12100,0.425000,76.009000,4.00000,232107.000000,False,C,major,C major,<NA>
1,Taylor Swift,False,2006-10-24,2.0,Picture To Burn,Taylor Swift,2006-10-24,0.658000,0.877000,7.000000,...,0.09620,0.821000,105.586000,4.00000,173067.000000,False,G,major,G major,<NA>
2,Taylor Swift,False,2006-10-24,3.0,Teardrops On My Guitar,Taylor Swift,2006-10-24,0.621000,0.417000,10.000000,...,0.11900,0.289000,99.953000,4.00000,203040.000000,False,A#,major,A# major,<NA>
3,Taylor Swift,False,2006-10-24,4.0,A Place In This World,Taylor Swift,2006-10-24,0.576000,0.777000,9.000000,...,0.32000,0.428000,115.028000,4.00000,199200.000000,False,A,major,A major,<NA>
4,Taylor Swift,False,2006-10-24,5.0,Cold As You,Taylor Swift,2006-10-24,0.418000,0.482000,5.000000,...,0.12300,0.261000,175.558000,4.00000,239013.000000,False,F,major,F major,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Beautiful Eyes,True,2008-07-15,2.0,Should've Said No (Alternate Version),Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,<NA>
243,Beautiful Eyes,True,2008-07-15,3.0,Teardrops On My Guitar (Acoustic Version),Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,<NA>
244,Beautiful Eyes,True,2008-07-15,4.0,Picture To Burn (Radio Edit),Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,<NA>
245,Beautiful Eyes,True,2008-07-15,5.0,I'm Only Me When I'm With You,Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,<NA>
246,Beautiful Eyes,True,2008-07-15,6.0,I Heart ?,Taylor Swift,2008-06-23,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,<NA>

In [50]:
taylor_song_df_processed["album_name"].unique()

array(['Taylor Swift', 'Fearless', "Fearless (Taylor's Version)",
       'Speak Now', 'Red', "Red (Taylor's Version)", '1989', 'reputation',
       'Lover', 'folklore', 'evermore', 'Midnights',
       'The Taylor Swift Holiday Collection', 'Beautiful Eyes'],
      dtype=object)

In [51]:
#Done fill all the null value in the dataframe
taylor_song_df_processed.to_csv(os.path.join(project_folder_path ,'Data/Processed/taylor_song_df_processed.csv' ), index = False)