####1.2 Import and Combining lyrics from kagle to match the album name and song title and saving it to local directory

In [ ]:
from google.colab import drive

drive.mount('/content/drive')
project_folder_path = "/content/drive/MyDrive/TaylorSwiftEras/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import kagglehub
import shutil
import os

# Download latest version
path = kagglehub.dataset_download("pradhanmanva/taylorswiftlyrics")

print("Path to dataset files:", path)
print(os.listdir(path))

Using Colab cache for faster access to the 'taylorswiftlyrics' dataset.
Path to dataset files: /kaggle/input/taylorswiftlyrics
['final_taylor_swift_lyrics.tsv']

In [ ]:
source_file : str = os.path.join(path, "final_taylor_swift_lyrics.tsv")

destination_folder : str = os.path.join(project_folder_path , "Data/Raw")


destination_file : str = os.path.join(
    destination_folder,
    "final_taylor_swift_lyrics.tsv"
)

shutil.copy(source_file, destination_folder)

print("CSV copied to:", destination_folder)

CSV copied to: /content/drive/MyDrive/TaylorSwiftEras/Data/Raw

In [ ]:
source_file : str = os.path.join(path, "final_taylor_swift_lyrics.tsv")

destination_folder : str = os.path.join(project_folder_path , "Data/Raw")


destination_file : str = os.path.join(
    destination_folder,
    "final_taylor_swift_lyrics.tsv"
)

shutil.copy(source_file, destination_folder)

print("CSV copied to:", destination_folder)

CSV copied to: /content/drive/MyDrive/TaylorSwiftEras/Data/Raw

In [ ]:
import pandas as pd
import csv

taylor_lyric_df = pd.read_csv(
    destination_file,
    sep="\t",
    engine="python",
    quoting=csv.QUOTE_NONE,
    on_bad_lines="skip"
)
taylor_lyric_df

,index,album,song_title,lyric,line_number,release_date
0,0,Lover,Lover,[Verse 1],0,2019-08-16
1,0,Lover,Lover,We could leave the Christmas lights up 'til Ja...,1,2019-08-16
2,0,Lover,Lover,"And this is our place, we make the rules",2,2019-08-16
3,0,Lover,Lover,"And there's a dazzling haze, a mysterious way ...",3,2019-08-16
4,0,Lover,Lover,Have I known you 20 seconds or 20 years?,4,2019-08-16
...,...,...,...,...,...,...
16475,469,Live from SoHo - EP,Picture to Burn (Live From SoHo),"Burn, burn, burn, baby, burn",40,2008-01-15
16476,469,Live from SoHo - EP,Picture to Burn (Live From SoHo),You're just another picture to burn,41,2008-01-15
16477,469,Live from SoHo - EP,Picture to Burn (Live From SoHo),"Baby, burn",42,2008-01-15
16478,469,Live from SoHo - EP,Picture to Burn (Live From SoHo),Thank you so much!,43,2008-01-15
16479,469,Live from SoHo - EP,Picture to Burn (Live From SoHo),Thank you!,44,2008-01-15

In [ ]:
bad_keywords = ["voice memo", "poem", "commentary", "interview"]

mask = ~taylor_lyric_df["song_title"].str.lower().str.contains(
    "|".join(bad_keywords),
    na=False
)

taylor_lyric_df = taylor_lyric_df[mask]

In [ ]:
taylor_lyric_df = taylor_lyric_df.groupby(["album","song_title"])["lyric"].apply(lambda x: " ".join(x)).reset_index()
taylor_lyric_df

,album,song_title,lyric
0,1989 (Deluxe),1989 [Liner Notes],"Prologue""These songs were once about my life. ..."
1,1989 (Deluxe),All You Had to Do Was Stay,[Verse 1] People like you always want back The...
2,1989 (Deluxe),Bad Blood,"[Chorus] ’Cause baby, now we've got bad blood ..."
3,1989 (Deluxe),Blank Space,"[Verse 1] Nice to meet you, where you been? I ..."
4,1989 (Deluxe),Clean,[Verse 1] The drought was the very worst (Oh-o...
...,...,...,...
333,reputation,Look What You Made Me Do,[Verse 1] I don't like your little games Don't...
334,reputation,New Year Day,[Verse 1] There's glitter on the floor after t...
335,reputation,Reputation [Prologue],Here's something I've learned about people. We...
336,reputation,So It Goes...,"[Verse 1] See you in the dark All eyes on you,..."
337,reputation,This Is Why We Can't Have Nice Things,[Verse 1] It was so nice throwing big parties ...

In [ ]:
taylor_lyric_df.to_csv(os.path.join(project_folder_path , "Data/Processed/taylor_lyric_df_processed.csv"))