####1.3 Merging both data containing title,album,and audio analysis with data containing the lyrics for the song

In [122]:
from google.colab import drive

drive.mount('/content/drive')
project_folder_path = '/content/drive/MyDrive/TaylorSwiftEras'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [123]:
import os
import pandas as pd

all_song_path = os.path.join(project_folder_path ,'Data/Processed/taylor_song_df_processed.csv' )
all_lyrics_path = os.path.join(project_folder_path, 'Data/Processed/taylor_lyric_df_processed.csv')

taylor_song_df = pd.read_csv(all_song_path)
taylor_lyrics_df = pd.read_csv(all_lyrics_path)

In [124]:
taylor_song_df.head()

,album_name,ep,album_release,track_number,track_name,artist,track_release,danceability,energy,key,...,liveness,valence,tempo,time_signature,duration_ms,explicit,key_name,mode_name,key_mode,lyrics
0,Taylor Swift,False,2006-10-24,1.0,Tim McGraw,Taylor Swift,2006-06-19,0.580,0.491,0.0,...,0.1210,0.425,76.009,4.0,232107.0,False,C,major,C major,NaN
1,Taylor Swift,False,2006-10-24,2.0,Picture To Burn,Taylor Swift,2006-10-24,0.658,0.877,7.0,...,0.0962,0.821,105.586,4.0,173067.0,False,G,major,G major,NaN
2,Taylor Swift,False,2006-10-24,3.0,Teardrops On My Guitar,Taylor Swift,2006-10-24,0.621,0.417,10.0,...,0.1190,0.289,99.953,4.0,203040.0,False,A#,major,A# major,NaN
3,Taylor Swift,False,2006-10-24,4.0,A Place In This World,Taylor Swift,2006-10-24,0.576,0.777,9.0,...,0.3200,0.428,115.028,4.0,199200.0,False,A,major,A major,NaN
4,Taylor Swift,False,2006-10-24,5.0,Cold As You,Taylor Swift,2006-10-24,0.418,0.482,5.0,...,0.1230,0.261,175.558,4.0,239013.0,False,F,major,F major,NaN

In [125]:
taylor_lyrics_df.head()

,Unnamed: 0,album,song_title,lyric
0,0,1989 (Deluxe),1989 [Liner Notes],"Prologue""These songs were once about my life. ..."
1,1,1989 (Deluxe),All You Had to Do Was Stay,[Verse 1] People like you always want back The...
2,2,1989 (Deluxe),Bad Blood,"[Chorus] ’Cause baby, now we've got bad blood ..."
3,3,1989 (Deluxe),Blank Space,"[Verse 1] Nice to meet you, where you been? I ..."
4,4,1989 (Deluxe),Clean,[Verse 1] The drought was the very worst (Oh-o...

In [126]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=taylor_lyrics_df)

https://docs.google.com/spreadsheets/d/1ZD1cpftL8da3yijIFj_nIqhZrrys0s48xWKgmK8_UXE/edit#gid=0

In [127]:
import re

def normalize_title(x):
    x = str(x).lower()

    # remove anything inside brackets
    x = re.sub(r"\(.*?\)", "", x)

    # remove punctuation
    x = re.sub(r"[^a-z0-9\s]", "", x)

    # normalize spaces
    x = re.sub(r"\s+", " ", x)

    return x.strip()

In [128]:
taylor_song_df["track_name_clean"] = taylor_song_df["track_name"].apply(normalize_title)

taylor_lyrics_df["song_title_clean"] = taylor_lyrics_df["song_title"].apply(normalize_title)

In [129]:

# Merge only the lyric column from df_grouped
taylor_merged_df = taylor_song_df.merge(
    taylor_lyrics_df[["song_title_clean", "lyric"]],
    left_on="track_name_clean",
    right_on="song_title_clean",
    how="left"
)

# Remove duplicate title column
taylor_merged_df = taylor_merged_df.drop(columns=["song_title_clean" , "track_name_clean" , "lyrics"])

# Preview
taylor_merged_df

,album_name,ep,album_release,track_number,track_name,artist,track_release,danceability,energy,key,...,liveness,valence,tempo,time_signature,duration_ms,explicit,key_name,mode_name,key_mode,lyric
0,Taylor Swift,False,2006-10-24,1.0,Tim McGraw,Taylor Swift,2006-06-19,0.580000,0.491000,0.000000,...,0.12100,0.425000,76.009000,4.00000,232107.000000,False,C,major,C major,[Verse 1] He said the way my blue eyes shined ...
1,Taylor Swift,False,2006-10-24,2.0,Picture To Burn,Taylor Swift,2006-10-24,0.658000,0.877000,7.000000,...,0.09620,0.821000,105.586000,4.00000,173067.000000,False,G,major,G major,"[Verse 1] State the obvious, I didn't get my p..."
2,Taylor Swift,False,2006-10-24,2.0,Picture To Burn,Taylor Swift,2006-10-24,0.658000,0.877000,7.000000,...,0.09620,0.821000,105.586000,4.00000,173067.000000,False,G,major,G major,"[Intro] This one's called ""Picture to Burn"" On..."
3,Taylor Swift,False,2006-10-24,3.0,Teardrops On My Guitar,Taylor Swift,2006-10-24,0.621000,0.417000,10.000000,...,0.11900,0.289000,99.953000,4.00000,203040.000000,False,A#,major,A# major,[Verse 1] Drew looks at me I fake a smile so h...
4,Taylor Swift,False,2006-10-24,3.0,Teardrops On My Guitar,Taylor Swift,2006-10-24,0.621000,0.417000,10.000000,...,0.11900,0.289000,99.953000,4.00000,203040.000000,False,A#,major,A# major,[Verse 1] Drew looks at me I fake a smile so h...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,Beautiful Eyes,True,2008-07-15,3.0,Teardrops On My Guitar (Acoustic Version),Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,[Verse 1] Drew looks at me I fake a smile so h...
273,Beautiful Eyes,True,2008-07-15,4.0,Picture To Burn (Radio Edit),Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,"[Verse 1] State the obvious, I didn't get my p..."
274,Beautiful Eyes,True,2008-07-15,4.0,Picture To Burn (Radio Edit),Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,"[Intro] This one's called ""Picture to Burn"" On..."
275,Beautiful Eyes,True,2008-07-15,5.0,I'm Only Me When I'm With You,Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,[Verse 1] Friday night beneath the stars In a ...
276,Beautiful Eyes,True,2008-07-15,6.0,I Heart ?,Taylor Swift,2008-06-23,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,NaN,NaN,NaN,NaN,[Verse 1] Wish I had concentrated They said lo...

In [130]:
sheet = sheets.InteractiveSheet(df=taylor_merged_df)

https://docs.google.com/spreadsheets/d/1VIvzlNOl8CTRt9U9tWEKtChssnml_ykx73rRSVpntko/edit#gid=0

In [131]:
taylor_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   album_name        277 non-null    object
 1   ep                277 non-null    bool
 2   album_release     277 non-null    object
 3   track_number      277 non-null    float64
 4   track_name        277 non-null    object
 5   artist            277 non-null    object
 6   track_release     277 non-null    object
 7   danceability      277 non-null    float64
 8   energy            277 non-null    float64
 9   key               277 non-null    float64
 10  loudness          277 non-null    float64
 11  mode              277 non-null    float64
 12  speechiness       277 non-null    float64
 13  acousticness      277 non-null    float64
 14  instrumentalness  277 non-null    float64
 15  liveness          277 non-null    float64
 16  valence           277 non-null    float64
 17  tempo             277 non-null    float64
 18  time_signature    277 non-null    float64
 19  duration_ms       277 non-null    float64
 20  explicit          264 non-null    object
 21  key_name          264 non-null    object
 22  mode_name         264 non-null    object
 23  key_mode          264 non-null    object
 24  lyric             214 non-null    object
dtypes: bool(1), float64(14), object(10)
memory usage: 52.3+ KB

In [132]:
taylor_merged_df = taylor_merged_df.dropna(subset=['lyric'])

string_cols = taylor_merged_df.select_dtypes(include ='object').columns

for col in string_cols:
    taylor_merged_df[col] = taylor_merged_df[col].fillna(taylor_merged_df[col].mode()[0])

taylor_merged_df = taylor_merged_df.drop_duplicates(subset="track_name")

taylor_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 0 to 276
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   album_name        183 non-null    object
 1   ep                183 non-null    bool
 2   album_release     183 non-null    object
 3   track_number      183 non-null    float64
 4   track_name        183 non-null    object
 5   artist            183 non-null    object
 6   track_release     183 non-null    object
 7   danceability      183 non-null    float64
 8   energy            183 non-null    float64
 9   key               183 non-null    float64
 10  loudness          183 non-null    float64
 11  mode              183 non-null    float64
 12  speechiness       183 non-null    float64
 13  acousticness      183 non-null    float64
 14  instrumentalness  183 non-null    float64
 15  liveness          183 non-null    float64
 16  valence           183 non-null    float64
 17  tempo             183 non-null    float64
 18  time_signature    183 non-null    float64
 19  duration_ms       183 non-null    float64
 20  explicit          183 non-null    bool
 21  key_name          183 non-null    object
 22  mode_name         183 non-null    object
 23  key_mode          183 non-null    object
 24  lyric             183 non-null    object
dtypes: bool(2), float64(14), object(9)
memory usage: 34.7+ KB

/tmp/ipykernel_3146/62111529.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  taylor_merged_df[col] = taylor_merged_df[col].fillna(taylor_merged_df[col].mode()[0])
/tmp/ipykernel_3146/62111529.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  taylor_merged_df[col] = taylor_merged_df[col].fillna(taylor_merged_df[col].mode()[0])

In [133]:
sheet = sheets.InteractiveSheet(df=taylor_merged_df)

https://docs.google.com/spreadsheets/d/1sJEzsqysEFSMk8lCePddpGQeLJjEWLOobr0reInqwow/edit#gid=0

In [134]:
taylor_merged_df.to_csv(os.path.join(project_folder_path, 'Data/Final/taylor_merged_df.csv'), index=False )